"""
Heber Light and Power record definitions.

field parameters for each record type giving:
name, beg/end locations and conversion method
(using list to preserve field order)
"""

from app_modules.freedom_utils import DotDict

DEFINITIONS = DotDict({
    'max_num_meters': 1,
    'max_num_charges': 16,  # only eight initially, + 2 for expansion
    'num_message_lines': 10,
    'months_of_history': 13,

    'months': {
        '01': 'Jan', '02': 'Feb', '03': 'Mar', '04': 'Apr',
        '05': 'May', '06': 'Jun', '07': 'Jul', '08': 'Aug',
        '09': 'Sep', '10': 'Oct', '11': 'Nov', '12': 'Dec',
        },

    'cycctl': [
        # ('REC_TYPE, 0, 6),
        ('BILL_DT', 6, 14),
        ('PEN_DUE_DT', 14, 22),
        # ('CYC_CD', 22,24),
        ],
    'master': [
        # ('REC_TYPE', 0, 6, None),
        ('ACCT', 6, 16, 'format_acc_no'),
        # ('TYPE_SRV, 16, 21, None),
        ('ADDR1(NAME)', 21, 56, None),
        ('ADDR2', 56, 91, None),
        ('ADDR3', 91, 126, None),
        ('ADDR4', 126, 161, None),
        ('ADDR5', 161, 196, None),
        ('ADDR6', 196, 231, None),
        ('SPEC_HAND_CD', 231, 233, None),
        ('CONS_CLASS_CD', 233, 234, None),
        ('SRV_ADDR', 234, 274, None),
        ('NBR_BILLS', 274, 275, None),
        ('ACCT_MULT', 275, 282, 'convert_acct_multipler'),
        ('EFT_SW', 282, 283, None),
        ('NO_CHECK', 283, 284, None),
        ('BANK_DRF_DT', 284, 292, 'convert_date'),
        ('SRV_DESC', 292, 332, None),
        ('PHONE_NBR', 332, 342, None),
        ('RATE_DESC', 342, 372, None),
        ('DIST_OFC_CD', 372, 375, None),
        ('BUDG_CATCH', 375, 376, None),
        ('ENV_GRP', 376, 386, None),
        ('CC_EXPIRE', 386, 387, None),
        # ('CUST_NBR', 387, 397, None),
        # ('ALLOC_YR', 397, 401, None),
        # ('ALLOC_AMT1', 401, 411, None),
        # ('ALLOC_AMT2', 411, 421, None),
        ],
    'history': [
        # ('REC_TYPE', 0, 6, None),
        # ('ACCT', 6, 16, None),
        # ('TYPE_SRV', 16, 21, None),
        ('PP{:02}_YR', 21, 25, None),
        ('PP{:02}_MO', 25, 27, None),
        ('PP{:02}_KWH', 27, 37, 'convert_to_integer'),
        ('PP{:02}_DAYS', 37, 40, 'convert_to_integer'),
        ('PP{:02}_AVG', 40, 48, 'convert_to_integer'),
        ],
    'meters': [
        # ('REC_TYPE', 0, 6, None),
        # ('ACCT', 6, 16, None),
        # ('TYPE_SRV', 16, 21, None),
        ('METER_{}', 21, 36, 'noop'),  # noop called to avoid lint warning
        ('RATE_{}', 36, 41, None),
        ('PREV_RDG_{}', 41, 50, 'convert_to_integer'),
        ('PRES_RDG_{}', 50, 59, 'convert_to_integer'),
        ('KWH_MULT_{}', 59, 69, 'convert_multipler'),
        ('DMD_MULT_{}', 69, 79, 'convert_multipler'),
        ('KWH_USAGE_{}', 79, 89, 'convert_to_integer'),
        ('DMD_ACTUAL_{}', 89, 102, 'convert_to_demand'),
        ('DMD_BILLED_{}', 102, 115, 'convert_to_demand'),
        ('DMD_RDG_{}', 115, 128, 'convert_to_demand'),
        ('FROM_DT_{}', 128, 136, 'convert_date'),
        ('TO_DT_{}', 136, 144, 'convert_date'),
        ('BOOK_{}', 144, 149, 'convert_to_integer'),
        ('SEQ_{}', 149, 154, 'convert_to_integer'),
        ('BILL_RDG_INFO_{}', 154, 155, None),
        ('CONTRACT_DMD_{}', 155, 165, 'convert_to_usage'),
        ('BILL_DAYS_{}', 165, 168, 'convert_to_integer'),
        ('KVAR_PREV_RDG_{}', 168, 180, 'convert_to_usage'),
        ('KVAR_PRES_RDG_{}', 180, 192, 'convert_to_usage'),
        ('KVAR_MULT_{}', 192, 206, 'convert_multipler'),
        ('BANKED_USAGE_{}', 206, 218, 'convert_to_usage'),
        # ('PFP', 218, 224, 'convert_multipler'),
        ],
    'charges': [
        # ('REC_TYPE', 0, 6, None),
        # ('ACCT', 6, 16, None),
        # ('TYPE_SRV', 15, 21, None),
        ('SERV_NAME_{:02}', 21, 60, None),
        ('SERV_AMT_{:02}', 69, 129, 'convert_to_currency'),
        ],
    'messages': [
        # ('REC_TYPE', 0, 6, None),
        # ('ACCT', 6, 16, None),
        # ('TYPE_SRV', 16, 21, None),
        ('MSG_{:02}', 21, 121, None),
        ],
    'acct_totals': [
        # ('REC_TYPE', 0, 6, None),
        # ('ACCT', 6, 16, None),
        # ('TYPE_SRV', 16, 21, None),
        ('PAST_DUE', 21, 31, 'convert_to_currency'),
        ('CURR_CHGS', 31, 41, 'convert_to_currency'),
        ('AMT_DUE', 41, 51, 'convert_to_currency'),
        ('GROSS_AMT', 51, 61, 'convert_to_currency'),
        ('BUDGET_AR_AMT', 61, 71, 'convert_to_currency'),
        ('BARCODE_DATA', 71, 100, None),
        ('CREDIT_BILL_FLAG', 100, 101, None),
        ('FINAL_BILL_FLAG', 101, 102, None),
        ('PAYMENTS', 102, 112, 'convert_to_currency'),
        ('ADJUSTMENTS', 112, 122, 'convert_to_currency'),
        ('PREV_BAL', 122, 132, 'convert_to_currency'),
        ('LATE_FEE', 132, 142, 'convert_to_currency'),
        ('LAST_PAY_DATE', 142, 150, 'convert_date'),
        ('DUE_DATE', 150, 158, 'convert_date'),
        ('SHUTOFF_MSG', 158, 218, None),
        ('DIRECT_PAY_MSG', 218, 278, None),
        ],
    'with_budget': [
        ('BUDGET_BILL_MSG', 278, 338, None),
        ('EBILL_SW', 338, 339, 'delete_bill'),
        ],
    'without_budget': [
        ('EBILL_SW', 278, 279, 'delete_bill'),
        ],
    'custom_headings': [
        'CYCLE',
        'ON_PEAK_USAGE', 'ON_PEAK_CHG',
        'OFF_PEAK_USAGE', 'OFF_PEAK_CHG',
        'TOTAL_PEAK_USE', 'TOTAL_PEAK_DMD',
        'BANKED_USE',
        ],
    })
