"""Xref of the XML element with the CSV column name for Discovery Bay CA.

CSV column names ending with '?' indicate possible multi value
(like multi meter reads)
"""

ACTIVE_ONLY = True
DELINQENT_ACCTS = True
ZERO_BALANCE = True  # Print zero bal accoutnts - True only for Feb 2022 bills
DIR_PAY_MSG = None

direct_pay = {
    'pay_date': 'Drft_dt', 'msg_col': 'message1',
    'message': '*Do not pay! Account Balance will be drawn from your bank on {draft_date}*.'  # noqa
    }

contracts = {  # have to construct data because unique extract not possible
    'code_field': 'Serv_code',
    '1001': 'Connection Charge',
    }

bill_extract = {  # XML attribs to extract & associated CSV column
    'Bill_dt': 'billdate',
    'Due_dt': 'duedate',
    'No': 'accnumber',
    'Name': 'company',
    'B_a1': 'address',
    'B_a2': 'address2',
    'B_city': 'city',
    'B_st': 'st',
    'B_zip': 'zip',
    'S_fr_dt': 'curbegdate',
    'S_to_dt': 'curenddate',
    'Ssa': 'serviceadd',
    'Pr_read': 'prevread?',
    'Cr_read': 'curread?',
    'Usage': 'usage?',
    'Days': 'daysbtwrd?',
    'Cr_read_date': 'currddt?',
    'Pr_read_date': 'prevrddt?',
    'Schedule': 'service_?',
    'Amount': 'amount_?',
    'M_no': 'meter_id?',
    'L_b_amt': 'prevbalamt',
    'T_pmts': 'curperamt',
    'T_adjs': 'adj_amt',
    'T_pens': 'pen_amt',
    'Due': 'acctbal',
    'Cons_prd': 'Cons_prd',
    'S_des': 'meter?',
    'Drf_cst': 'directpay',
    'Orig_amt': 'contrctamt',
    'Curr_charge': 'contrctbil',
    'arrear': 'past_due_amt',

    # feilds below only used for decision making and not stored in CSV
    'Drft_dt': 'Drft_dt',
    'Serv_code': 'Serv_code',
    }

blank_usage_services = [
    'Account Charge',
    'Sewer',
    ]

currency_fields = [
    'prevbalamt',
    'curperamt',
    'adj_amt',
    'pen_amt',
    'acctbal',
    'contrctbil',
    'contrctamt',
    'past_due_amt',
    # shut-off fields
    'ARREARBAL',
    'ACCNTBAL',
    ]

bill_literals = {  # CSV columns that have fixed literal values
    'prevbaltit': 'PREVIOUS BALANCE',
    'curperpymt': 'PAYMENTS',
    'adj_title': 'ADJUSTMENTS',
    'penalty_title': 'PENALTIES',
    'past_due_title': 'PAST DUE',
    'payamttitl': 'PAY THIS AMOUNT',
    'usagetitl1': '1',
    'usagetitl2': '2',
    'usagetitl3': '3',
    'usagetitl4': '4',
    'usagetitl5': '5',
    'usagetitl6': '6',
    'usagetitl7': '7',
    'usagetitl8': '8',
    'usagetitl9': '9',
    'usagetit10': '10',
    'usagetit11': '11',
    'usagetit12': '12',
    'el_title1': '1',
    'el_title2': '2',
    'el_title3': '3',
    'el_title4': '4',
    'el_title5': '5',
    'el_title6': '6',
    'el_title7': '7',
    'el_title8': '8',
    'el_title9': '9',
    'el_title10': '10',
    'el_title11': '11',
    'el_title12': '12',
    }

bill_headings = [
    'billdate',
    'duedate',
    'accnumber',
    'baraccnum',
    'company',
    'address',
    'address2',
    'city',
    'st',
    'zip',
    'curbegdate',
    'curenddate',
    'serviceadd',
    'prevread1',
    'curread1',
    'currusage1',
    'prevread2',
    'curread2',
    'usage2',
    'prevread3',
    'curread3',
    'usage3',
    'prevread4',
    'curread4',
    'usage4',
    'prevread5',
    'curread5',
    'usage5',
    'prevread6',
    'curread6',
    'usage6',
    'prevread7',
    'curread7',
    'usage7',
    'prevread8',
    'curread8',
    'usage8',
    'prevbaltit',
    'prevbalamt',
    'curperpymt',
    'curperamt',
    'adj_title',
    'adj_amt',
    'service_1',
    'amount_1',
    'service_2',
    'amount_2',
    'service_3',
    'amount_3',
    'service_4',
    'amount_4',
    'service_5',
    'amount_5',
    'service_6',
    'amount_6',
    'service_7',
    'amount_7',
    'service_8',
    'amount_8',
    'service_9',
    'amount_9',
    'service_10',
    'amount_10',
    'contrctbil',
    'contrctamt',
    'directpay',
    'payamttitl',
    'acctbal',
    'currusage',
    'usagepri1',
    'usagetitl1',
    'usagepri2',
    'usagetitl2',
    'usagepri3',
    'usagetitl3',
    'usagepri4',
    'usagetitl4',
    'usagepri5',
    'usagetitl5',
    'usagepri6',
    'usagetitl6',
    'usagepri7',
    'usagetitl7',
    'usagepri8',
    'usagetitl8',
    'usagepri9',
    'usagetitl9',
    'usagepri10',
    'usagetit10',
    'usagepri11',
    'usagetit11',
    'usagepri12',
    'usagetit12',
    'shutoffmsg',
    'message1',
    'message2',
    'message3',
    'message4',
    'prevread9',
    'curread9',
    'usage9',
    'prevread10',
    'curread10',
    'usage10',
    'service_11',
    'amount_11',
    'el_usage',
    'el_usage1',
    'el_title1',
    'el_usage2',
    'el_title2',
    'el_usage3',
    'el_title3',
    'el_usage4',
    'el_title4',
    'el_usage5',
    'el_title5',
    'el_usage6',
    'el_title6',
    'el_usage7',
    'el_title7',
    'el_usage8',
    'el_title8',
    'el_usage9',
    'el_title9',
    'el_usage10',
    'el_title10',
    'el_usage11',
    'el_title11',
    'el_usage12',
    'el_title12',
    'meter1',
    'meter2',
    'meter3',
    'meter4',
    'meter5',
    'meter6',
    'meter7',
    'meter8',
    'meter9',
    'meter10',
    'meter_id1',
    'meter_id2',
    'meter_id3',
    'meter_id4',
    'meter_id5',
    'meter_id6',
    'meter_id7',
    'meter_id8',
    'meter_id9',
    'meter_id10',
    'imbarcode',
    'endorse',
    'sequence',
    'cont_id',
    'traymark_',
    'numb_days',
    'avg_kwh',
    'demand1',
    'demand2',
    'demand3',
    'demand4',
    'demand5',
    'demand6',
    'demand7',
    'demand8',
    'prevrddt1',
    'prevrddt2',
    'prevrddt3',
    'prevrddt4',
    'prevrddt5',
    'prevrddt6',
    'prevrddt7',
    'prevrddt8',
    'currddt1',
    'currddt2',
    'currddt3',
    'currddt4',
    'currddt5',
    'currddt6',
    'currddt7',
    'currddt8',
    'daysbtwrd1',
    'daysbtwrd2',
    'daysbtwrd3',
    'daysbtwrd4',
    'daysbtwrd5',
    'daysbtwrd6',
    'daysbtwrd7',
    'daysbtwrd8',
    'penalty_title',
    'pen_amt',
    'past_due_title',
    'past_due_amt',
    ]

late_pay_headings = [
    'NAME',
    'ADDRESS_1',
    'ADDRESS_2',
    'CITY',
    'STATE',
    'ZIP',
    'MAILINGDAT',
    'CUSTNUM',
    'SERVICEAD',
    'SHUTOFFDAT',
    'ARREARBAL',
    'ACCNTBAL',
    'SHUTOFFDA2',
    ]

late_pay_extract = {
    'Name': 'NAME',
    'Addr1': 'ADDRESS_1',
    'Addr2': 'ADDRESS_2',
    'City': 'CITY',
    'State': 'STATE',
    'Zip': 'ZIP',
    'Notice_dt': 'MAILINGDAT',
    'No': 'CUSTNUM',
    'Addr': 'SERVICEAD',
    'Cutoff_dt': 'SHUTOFFDAT',
    'Past_due': 'ARREARBAL',
    'Acct_bal': 'ACCNTBAL',
    'DueDate_dt': 'SHUTOFFDA2',
    }
