"""Definition of various record types in Waterford bill file."""


NEG_SIGN = 'CR'
FIELDS = {
    'BILL': [
        'Rec Type',
        'Bill ID',
        'Seq #',
        'Bill Type',
        'Account Number',
        'Account Suffix',
        'CID#',
        'Account Name',
        'Route',
        'Sequence',
        'Service Address 1',
        'Service Address 2',
        'Service City',
        'Service State',
        'Service Zip',
        'Service ZIP4',
        'Mail to Name',
        'Mail to Attention',
        'Mail to Address 1',
        'Mail to Address 2',
        'Mail to City',
        'Mail to State',
        'Mail to Zip',
        'Mail to ZIP4',
        'Mail to Carrier Route',
        'Mail to Delivery Point',
        'IMB Full',
        'Bill Date',
        'Discount Date',
        'Due Date',
        'Service From Date',
        'Service To Date',
        'Previous Balance*',
        'Payments*',
        'Adjustments*',
        'Past Due Balance*',
        'Penalties Applied*',
        'Interest Applied*',
        'Lien Amount*',
        'Current Bill Amount*',
        'Balance Due*',
        'Penalty Amount*',
        'ACH Date',
        'ACH Amount*',
        'Discounted Amount*',
        'Extended Discount Date',
        'Extended Discount Amount*',
        'Last Payment Date',
        'Last Payment Amount*',
        'Extended Discount Name',
        'EDU',
        'Municipality Name',
        'Municipality Code',
        'Units Override',
        'Discounts Taken*',
        'Applied Deposits and Interest*',
        'Shutoff Date',
        'Bill Amount*',
        'Penalty Amount*',
        'Interest Amount*',
        'Leak Detection',
        'Payplan Amount*',
        'OCR Scanline',
        'Ach Flag',
        # 'Parcel Number',
        # 'Tax ID',
        # 'Reserved',
        # 'Reserved',
        # 'Reserved',
        # 'Reserved'
        ],
    'MTR': [
        'Rec Type',
        'Bill ID',
        'Seq #',
        'Meter Number',
        'Meter Type',
        'Display Order',
        'Read Date',
        'Previous Reading',
        'Current Reading',
        'Usage',
        'Units',
        'Reading Type',
        'Service Type',
        'Meter Exchange Type',
        'Services',
        'Demand Units',
        'Demand Reading',
        'Previous Reading Date',
        'Meter Size Text',
        # 'Reserved',
        # 'Reserved',
        # 'Reserved',
        # 'Reserved',
        # 'Reserved'
        ],
    'SVC': [
        'Rec Type',
        'Bill ID',
        'Seq #',
        'Display Order',
        'Service',
        'Type',
        'Amount*',
        'Description',
        'Quantity',
        'Calculation Type',
        'Service Usage',
        # 'Reserved ',
        # 'Reserved ',
        # 'Reserved ',
        # 'Reserved ',
        # 'Reserved '
        ],
    'ADJ': [
        'Rec Type',
        'Date',
        'Bill Heading',
        'Placement',
        'Service',
        'Type',
        'Amount*',
        'Description',
        # 'Reserved',
        # 'Reserved',
        # 'Reserved',
        # 'Reserved',
        # 'Reserved'
        ],
    'MSG': [
        'Rec Type',
        'Bill ID',
        'Seq #',
        'Message Type',
        'Message Text',
        # 'Reserved',
        # 'Reserved',
        # 'Reserved',
        # 'Reserved',
        # 'Reserved'
        ],
    'LOAN': [
        'Rec Type',
        'Title',
        'Principle Service Title',
        'Original Amount*',
        'Principle Remaining*',
        'Interest Remaining*',
        'Payment Due*',
        'Interest Due*',
        'Bill Pay Amount*',
        'Interest Pay Amount*',
        'Bill Adjustment Amount*',
        'Interest Adjustment Amount*',
        # 'Reserved',
        # 'Reserved',
        # 'Reserved',
        # 'Reserved',
        # 'Reserved'
        ],
    }
